usodiccionario: usodiccionario.cpp
	g++ -g -Wall -pedantic -o usodiccionario usodiccionario.cpp
mrproper:
	rm usodiccionario
run: 
	
	g++ -g -o usodiccionario usodiccionario.cpp
	./usodiccionario